# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14r6_CbEl_Pa3Z1saiiQwgpaVukvbagFi
"""


import streamlit as st
import numpy as np
import pandas as pd
import requests
import matplotlib.pyplot as plt
import os
from sklearn.preprocessing import MinMaxScaler

# Optional TensorFlow import (safe)
try:
    from tensorflow.keras.models import load_model
    TF_AVAILABLE = True
except:
    TF_AVAILABLE = False

# ---------------- UI CONFIG ----------------
st.set_page_config(page_title="Weather Forecast App", layout="centered")

st.title("🌦️ Weather Forecast App")
st.write("Predict next 10 days weather using Deep Learning")

# ---------------- INPUT ----------------
city = st.text_input("Enter City Name", "Delhi")
API_KEY = "f530270436ed7cd9a06324c89c953281"

# ---------------- LOAD MODEL ----------------
@st.cache_resource
def load_my_model():
    model_path = "weather_model.h5"
    
    if not os.path.exists(model_path):
        st.error(f"❌ Model file '{model_path}' not found in the repository!")
        return None
        
    try:
        from tensorflow.keras.models import load_model
        return load_model(model_path, compile=False)
    except Exception as e:
        st.error(f"❌ Error loading model: {e}")
        return None

model = load_my_model()

# ---------------- LOAD DATA ----------------
@st.cache_data
def load_data():
    # Use absolute path for Google Colab environment
    csv_path = "weather.csv"
    if os.path.exists(csv_path):
        return pd.read_csv(csv_path)
    return None

df = load_data()

# Check if dataframe was loaded successfully to avoid NoneType error
if df is None:
    st.error("❌ weather.csv file not found at weather.csv")
    st.stop()

# ---------------- PREPROCESS ----------------
# Ensure these column names match your weather.csv exactly
required_cols = ['meantemp', 'humidity', 'meanpressure', 'wind_speed']

try:
    # Extract values for scaling
    data = df[required_cols].values
except KeyError as e:
    st.error(f"❌ Column mismatch! Please check if {e} exists in your CSV.")
    st.stop()

scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(data)
# ---------------- BUTTON ----------------
if st.button("🚀 Get Forecast"):

    # ----------- LIVE WEATHER -----------
    try:
        url = f"http://api.openweathermap.org/data/2.5/weather?q={city}&appid={API_KEY}&units=metric"
        res = requests.get(url).json()

        if res.get("cod") != 200:
            st.error("❌ Invalid API Key or City")
        else:
            # Rainfall Check 
            rain = 0
            if 'rain' in res:
                rain = res['rain'].get('1h', 0)

            st.subheader("🌍 Current Weather")
            
            # Ab hum 3 columns banayenge taaki 5 metrics achhe se adjust ho jayein
            col1, col2, col3 = st.columns(3)
            
            with col1:
                st.metric(label="🌡️ Temperature", value=f"{res['main']['temp']} °C")
                st.metric(label="🌍 Pressure", value=f"{res['main']['pressure']} hPa")
                
            with col2:
                st.metric(label="💧 Humidity", value=f"{res['main']['humidity']} %")
                st.metric(label="🌬️ Wind Speed", value=f"{res['wind']['speed']} m/s")
                
            with col3:
                # Rainfall ko UI mein dikhane ke liye metric add kar diya
                st.metric(label="🌧️ Rainfall (1h)", value=f"{rain} mm")

    except Exception as e:
        st.error(f"❌ API Error: {e}")

    # ----------- PREDICTION -----------
    st.subheader("📅 Next 10 Days Temperature Forecast")

    if model is None:
        st.warning("⚠️ Model not found / TensorFlow not available → Showing dummy forecast")

        temp_pred = np.random.uniform(20, 35, 10)

    else:
        try:
            last_seq = scaled_data[-30:]
            last_seq = last_seq.reshape(1, 30, 4)

            pred = model.predict(last_seq)

            temp_pred = scaler.inverse_transform(
                np.concatenate([pred.reshape(-1,1), np.zeros((10,3))], axis=1)
            )[:,0]

        except:
            st.error("❌ Model prediction failed")
            temp_pred = np.random.uniform(20, 35, 10)

    # ----------- TABLE -----------
    forecast_df = pd.DataFrame({
        "Day": [f"Day {i+1}" for i in range(10)],
        "Temperature (°C)": temp_pred
    })

    st.dataframe(forecast_df)

    # ----------- GRAPH -----------
    st.subheader("📈 Forecast Graph")

    fig, ax = plt.subplots()
    ax.plot(temp_pred)
    ax.set_xlabel("Days")
    ax.set_ylabel("Temperature")
    ax.set_title("Next 10 Days Forecast")

    st.pyplot(fig)

# ---------------- SIDEBAR ----------------
st.sidebar.header("📌 About Project")

st.sidebar.write("""
This project uses:
- RNN + LSTM model
- Weather dataset
- OpenWeather API

Features:
- Live weather data
- 10-day forecast
- Graph visualization
""")

