# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14r6_CbEl_Pa3Z1saiiQwgpaVukvbagFi
"""


import streamlit as st
import numpy as np
import pandas as pd
import requests
import matplotlib.pyplot as plt
import os
from sklearn.preprocessing import MinMaxScaler

# Optional TensorFlow import (safe)
try:
    from tensorflow.keras.models import load_model
    TF_AVAILABLE = True
except:
    TF_AVAILABLE = False

# ---------------- UI CONFIG ----------------
st.set_page_config(page_title="Weather Forecast App", layout="centered")

st.title("🌦️ Weather Forecast App (RNN + LSTM)")
st.write("Predict next 10 days weather using Deep Learning")

# ---------------- INPUT ----------------
city = st.text_input("Enter City Name", "Delhi")
API_KEY = st.text_input("Enter OpenWeather API Key", type="password")

# ---------------- LOAD MODEL ----------------
@st.cache_resource
def load_my_model():
    if not TF_AVAILABLE:
        return None
    if not os.path.exists("weather_model.h5"):
        return None
    return load_model("weather_model.h5",compile = False)

model = load_my_model()

# ---------------- LOAD DATA ----------------
@st.cache_data
def load_data():
    # Use absolute path for Google Colab environment
    csv_path = "/content/weather.csv"
    if os.path.exists(csv_path):
        return pd.read_csv(csv_path)
    return None

df = load_data()

# Check if dataframe was loaded successfully to avoid NoneType error
if df is None:
    st.error("❌ weather.csv file not found at /content/weather.csv")
    st.stop()

# ---------------- PREPROCESS ----------------
# Ensure these column names match your weather.csv exactly
required_cols = ['meantemp', 'humidity', 'meanpressure', 'wind_speed']

try:
    # Extract values for scaling
    data = df[required_cols].values
except KeyError as e:
    st.error(f"❌ Column mismatch! Please check if {e} exists in your CSV.")
    st.stop()

scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(data)

# ---------------- BUTTON ----------------
if st.button("🚀 Get Forecast"):

    # ----------- LIVE WEATHER -----------
    try:
        url = f"http://api.openweathermap.org/data/2.5/weather?q={city}&appid={API_KEY}&units=metric"
        res = requests.get(url).json()

        if res.get("cod") != 200:
            st.error("❌ Invalid API Key or City")
        else:
            live_data = {
                "🌡️ Temperature (°C)": res["main"]["temp"],
                "💧 Humidity (%)": res["main"]["humidity"],
                "🌍 Pressure (hPa)": res["main"]["pressure"],
                "🌬️ Wind Speed (m/s)": res["wind"]["speed"]
            }

            st.subheader("🌍 Current Weather")
            st.json(live_data)

    except:
        st.error("❌ API Error")

    # ----------- PREDICTION -----------
    st.subheader("📅 Next 10 Days Temperature Forecast")

    if model is None:
        st.warning("⚠️ Model not found / TensorFlow not available → Showing dummy forecast")

        temp_pred = np.random.uniform(20, 35, 10)

    else:
        try:
            last_seq = scaled_data[-30:]
            last_seq = last_seq.reshape(1, 30, 4)

            pred = model.predict(last_seq)

            temp_pred = scaler.inverse_transform(
                np.concatenate([pred.reshape(-1,1), np.zeros((10,3))], axis=1)
            )[:,0]

        except:
            st.error("❌ Model prediction failed")
            temp_pred = np.random.uniform(20, 35, 10)

    # ----------- TABLE -----------
    forecast_df = pd.DataFrame({
        "Day": [f"Day {i+1}" for i in range(10)],
        "Temperature (°C)": temp_pred
    })

    st.dataframe(forecast_df)

    # ----------- GRAPH -----------
    st.subheader("📈 Forecast Graph")

    fig, ax = plt.subplots()
    ax.plot(temp_pred)
    ax.set_xlabel("Days")
    ax.set_ylabel("Temperature")
    ax.set_title("Next 10 Days Forecast")

    st.pyplot(fig)

# ---------------- SIDEBAR ----------------
st.sidebar.header("📌 About Project")

st.sidebar.write("""
This project uses:
- RNN + LSTM model
- Weather dataset
- OpenWeather API

Features:
- Live weather data
- 10-day forecast
- Graph visualization
""")

